version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./notes.db
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    networks:
      - notes-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - notes-network
    depends_on:
      - backend

volumes:
  backend_data:

networks:
  notes-network:
    driver: bridge